### ISSUE TITLE
Doesn't work with Foundry 9

### ISSUE THREAD

**Issue by trev33b** [Reaver01/mwpm#8]
@Reaver01, I've found this to be an invaluable module to aid in wall creation.  I've recently upgraded to Foundry 9 and noticed this module doesn't work.  It looks like @Sk1mble may have a pull request that would solve this.  Can we get that pull request reviewed & released if it works?

**Comment by Reaver01** [comment]
@trev33b. I just merged the PR. I'll give it a test on one of my updated foundry worlds and if it works I'll make a new release for this.

**Comment by Reaver01** [comment]
It looks like there is more to it than that PR.

**Comment by Reaver01** [comment]
```
mwpm.js:69 Uncaught (in promise) TypeError: scene.updateEmbeddedEntity is not a function
    at hookOnpreUpdateWall (VM1575 mwpm.js:69:25)
    at VM1575 mwpm.js:83:23
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:10215:47)
    at async ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:10146:22)
    at async Function.updateDocuments (document.mjs:373:21)
    at async WallDocument.update (document.mjs:456:21)
```
It looks like updateEmbeddedEntity is deprecated.

**Comment by Reaver01** [comment]
Fixed in latest release!

**Comment by trev33b** [comment]
Sweet, thanks for the quick turnaround!
